# Generated by Django 3.2.3 on 2021-05-21 20:55

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nmkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='language',
            field=models.CharField(blank=True, default='sr-Latn', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Belgrade'),
        ),
    ]
