# Generated by Django 4.1 on 2022-10-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmkapp", "0002_auto_20210521_2055"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="pledged_donation",
            field=models.BooleanField(default=False),
        ),
    ]
