from django.urls import re_path, include
from nmkapp import views
from django.contrib.auth.views import logout_then_login, PasswordChangeView

urlpatterns = [
    re_path(r'^$', views.home),
    re_path(r'^register$', views.register),
    re_path(r'^register/success$', views.register_success),
    re_path(r'^activate$', views.activation),
    re_path(r'^forgotpassword', views.forgotpassword),
    re_path(r'^login/$', views.CustomLoginView.as_view(template_name='login.html', extra_context={'no_menu': True}),
        name='login'),
    re_path('', include('social_django.urls', namespace='social')),
    re_path(r'^requestdisplayname$', views.request_display_name, name='request_display_name'),
    re_path(r'^logout$', logout_then_login),
    re_path(r'^profile/reset$', views.reset_password),
    re_path(r'^profile/password$', PasswordChangeView.as_view(template_name='password.html', success_url='/')),
    #re_path(r'^profile/password$', password_change, {"template_name": "password.html", "post_change_redirect": "/"}),
    re_path(r'^profile/create_password$', views.create_password, name='create_password'),
    re_path(r'^profile$', views.profile),
    re_path(r'^crew', views.crew),
    re_path(r'^results$', views.results),
    re_path(r'^results/league$', views.results_league),
    re_path(r'^results/cup$', views.results_cup),
    re_path(r'^standings$', views.standings),
    re_path(r'^roundstandings/(?P<round_id>\d+)$', views.round_standings),
    re_path(r'^groups/(?P<group_id>\d+)/leave', views.group_leave),
    re_path(r'^groups/(?P<group_id>\d+)/delete', views.group_delete),
    re_path(r'^proposition$', views.proposition),
    re_path(r'^about$', views.about),
    re_path(r'^privacy$', views.privacy),
    re_path(r'^terms$', views.terms),
    re_path(r'^paypal$', views.paypal),
    re_path(r'^landing$', views.landing),
    re_path(r'^admin/rounds$', views.admin_rounds),
    re_path(r'^admin/rounds/edit$', views.admin_rounds_edit),
    re_path(r'^admin/matches$', views.admin_matches),
    re_path(r'^admin/matches/edit$', views.admin_matches_edit),
    re_path(r'^admin/results$', views.admin_results),
    re_path(r'^admin/results/change/(?P<match_id>\d+)$', views.admin_results_change),
    re_path(r'^admin/points$', views.admin_points),
]
